### ISSUE TITLE
Individual .ics files

### ISSUE THREAD

**Issue by S1SYPHOS** [mzur/kirby-calendar-plugin#24]
Hey there,
is it possible to generate an ical file for every event as single file? I want to loop through all events and add a download link next to each event with its individual `.ics` file.

Thanks, much appreciated plugin so far.

**Comment by mzur** [comment]
Sure, just take the [ical Snippet](https://github.com/mzur/kirby-calendar-plugin/blob/ea8311aa7ceb651b92de00540120c7c09173be77/snippets/calendar-ical.php) as an example. Instead of [looping over all events](https://github.com/mzur/kirby-calendar-plugin/blob/ea8311aa7ceb651b92de00540120c7c09173be77/snippets/calendar-ical.php#L5-L13) you can modify it to show only a single event, too.

**Comment by S1SYPHOS** [comment]
Yeah, but how to include a link to a file, generated by the modified snippet? Sorry, I am new to kirby and still learning ..

**Comment by mzur** [comment]
If you create your events as subpages instead of entries in a structure field you can use [content representations](https://getkirby.com/docs/developer-guide/advanced/representations). Say you have an `/events` page and an `/events/myevent` event, then you can output the event as ical with this URL `/events/myevent.ics`.
